name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./server

      # Add backend tests here if you have any
      # - name: Run Backend Tests
      #   run: npm test
      #   working-directory: ./server

      - name: Build Backend (if applicable)
        run: npm run build
        working-directory: ./server

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Frontend
        run: npm run build
        working-directory: ./client

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Backend
        run: |
          echo "Deploying Node.js backend..."
          # Add deployment commands for backend here

      - name: Deploy Frontend
        run: |
          echo "Deploying React frontend..."
          # Add deployment commands for frontend here 